.TH ACERWANG 7
.SH NAME
Acer Wang \- Electrical Engineering Student | Nom Nom Expert
.SH SYNOPSIS
acerwang [-c] [-e [school][,...]] [-o] [-p [project][,...]] [-s] [-v] [-w]
acerwang -a
acerwang -g
.SH SUMMARY
.SH DESCRIPTION
.B -a, --all
Setting this option will display everything that this program has to offer.
The program will return an error if other options are set.

.B -c, --contact
This option returns my contact information.

.B -e, --education [school]
Returns my post-secondary education history.
Arguments you can pass:

waterloo, toronto, taipei

If no arguments are passed, then all education history will be displayed.

.B -g, --getpdf
Returns a url string of my resume in PDF format. The program will return an error if other options are set.

.B -h, --help
Displays a short help page to get you started.

.B -m, --me
You can see what I look like, in an ASCII art!

.B -o, --other
A bit more things I like to share with you about me.

.B -p, --projects [project]
List of my mentionable projects.
Arguments you can pass:

printer, uwchat, blimp, pinball, psp

If no arguments are passed, then all projects will be displayed.

.B -s, --skill
Setting this option returns a summary of my skillset.

.B -v, --volunteer
Returns my volunteer experiences.

.B -w, --work [work]
Returns my work experiences. Arguments you can pass: communitech, irdeto. If no arguments are passed, then all work experience will be displayed.
.SH AUTHOR
Shamelessly written by Acer Chi Wang, Copyright 2015. For more information, visit http://www.acer.io
.SH OTHER
Download the program at https://github.com/acerism/resume-linux.